### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by UserXGnu** [bbht-br/phaton#3]
Hey guys,

Why don't you develop this on top of [virgulino's](https://github.com/lampiaosec/virgulino-ruby/tree/ruby) abstraction layer? I mean, it already has a full API for stuff like this with plugin support and so on..so why not?

**Comment by HeitorG** [comment]
Hi @UserXGnu.
The atual version of Phaton is still is a basic structure.
It is not just that!!
The Virgulino will not meet our needs in the future...
Thank you for your suggestion.

**Comment by UserXGnu** [comment]
Virgulino's API aims to be an abstraction layer to any kind of tool with encrytion, decryption or stegnography purpose. The actual version of virgulinho on branch [ruby](https://github.com/lampiaosec/virgulino-ruby/tree/ruby), support's plugins in an easy way, anyone can easly develop a plugin to encrypt/decrypt or break a crypto and insert on plugins directory and virgulinhos API will automatically recognize this plugin and will be able to use it. So, based on the Phaton project tittle 

> A simple tool to decrypt ultiple types of hashes

Virgulino's API fits perfectly...

**Comment by HeitorG** [comment]
Like I said... 
Today the Phaton this on a basic structure.
In the future we will need this structure.

**Comment by UserXGnu** [comment]
Alright then.
